# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - passive-microservice-ecalderc

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_88ccb89f37d74c6cbaea9ed17fa0781f }}
        password: ${{ secrets.AzureAppService_ContainerPassword_795d076341a04345a986af490e2e538f }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_88ccb89f37d74c6cbaea9ed17fa0781f }}/ebercalderon/passive-microservice:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'passive-microservice-ecalderc'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_aed33d65987d477d93e612dc11c7efb0 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_88ccb89f37d74c6cbaea9ed17fa0781f }}/ebercalderon/passive-microservice:${{ github.sha }}'